I extended the application
mariuspopovici/starlimsvscode pull request #19
Opened 2023-06-23 13:02 UTC by MrDoe

- Display the extension on the activity bar of vscode
- Automatically copy selected files to local folder and open it
- Check in and out items (works only on tree view so far)

2023-06-24 12:19 UTC, mariuspopovici commented on .vscode/settings.json
> +    "STARLIMS.url": "http://161.42.232.235/starlims",
let's leave these out from the default settings file

2023-06-24 12:48 UTC, mariuspopovici requested changes
Thanks for the PR! Looks great!


Couple of comments:
1) I would like to keep the HTMLFORMGUIDE feature available. See the review comments bellow.
2) It would be nice to keep the tree item icons. I see you removed those.

2023-06-24 12:48 UTC, mariuspopovici commented on src/backend/SCM_API/Server Scripts/SCM_API/GetCode.srvscr
> -	:CASE oEnterpriseItem:Type == "HTMLFORMGUIDE";
I'd like to keep this in and allow editing the on-boarding guide resource for forms. This sort of a not widely known feature which allows you to build an on-boarding script for the current application and it's activated with the Guide Me button. The onboarding script is saved as a form resource item but it's very difficult to edit in the designer... since it's basically only accessible from the form resource editor.

![image](https://github.com/mariuspopovici/starlimsvscode/assets/6911793/472d4bee-f8ce-4d85-9d6d-d4efdc42fdc6)


See the PR https://github.com/mariuspopovici/starlimsvscode/pull/17

2023-06-24 12:48 UTC, mariuspopovici commented on src/backend/SCM_API/Server Scripts/SCM_API/Utils.srvscr
> -						:IF sFormCodeType == "Guide";
let's keep the Guide option available.

2023-06-24 12:48 UTC, mariuspopovici commented on src/providers/enterpriseTreeDataProvider.ts
> -    } else if (item.checkedOutBy) {
I think the tree item icons are helpful, no? why remove them?

2023-06-24 12:48 UTC, mariuspopovici commented on src/backend/SCM_API/Server Scripts/SCM_API/GetEnterpriseItems.srvscr
> -			AAdd(aItems, {oRow["FORMNAME"] + " [Guide]", "HTMLFORMGUIDE", "JSON", sURI + "/Guide/" + oRow["FORMNAME"], oRow["CHECKEDOUTBY"]});
Let's leave the Guide option in

2023-06-24 14:29 UTC, mariuspopovici approved these changes

2023-06-24 14:30 UTC, merged

2023-06-26 05:46 UTC, MrDoe commented on src/backend/SCM_API/Server Scripts/SCM_API/GetCode.srvscr
> -	:CASE oEnterpriseItem:Type == "HTMLFORMGUIDE";
Okay, I actually didn't know that feature. I mean, I know the "Guide Me" button, but didn't know how to program it. But it should be very useful for beginners.

2023-06-26 05:56 UTC, MrDoe commented on src/providers/enterpriseTreeDataProvider.ts
> -    } else if (item.checkedOutBy) {
Newer versions of VS Code throw an error and don't show the icons anymore, so as a workaround, I switched back to the inegrated icons. I guess there were some breaking changes in the ExtensionHost-Class. Maybe we should try this out: https://github.com/microsoft/vscode/issues/150610

2023-06-26 05:58 UTC, MrDoe commented on .vscode/settings.json
> +    "STARLIMS.url": "http://161.42.232.235/starlims",
Of course, I forgot this. ;)

2023-06-26 06:23 UTC, MrDoe commented on src/providers/enterpriseTreeDataProvider.ts
> -    } else if (item.checkedOutBy) {
Okay, I pulled your changes, but now your custom icons work again. So forget what I wrote above. I don't know what the problem was.